apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  openmetadata-mysql-password: {{ .Values.secrets.openmetadataMysqlPassword | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
type: Opaque
data:
  openmetadata-airflow-password: {{ .Values.secrets.airflowPassword | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-mysql-secrets
type: Opaque
data:
  airflow-mysql-password: {{ .Values.secrets.airflowMysqlPassword | b64enc }}
