apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
        - name: mysql
          image: "mysql:{{ .Values.mysql.version }}"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretName }}
                  key: mysql-root-password
            - name: MYSQL_USER
              value: {{ .Values.mysql.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
            - mountPath: /docker-entrypoint-initdb.d
              name: initdb-scripts
      volumes:
        - name: initdb-scripts
          configMap:
            name: {{ .Values.mysql.configMapName }}
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
        namespace: {{ .Values.namespace }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.mysql.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.mysql.storageSize }}
