apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.streamParkPersistent.name }}
  labels:
    app.kubernetes.io/name: streampark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.streamParkPersistent.size }}
  storageClassName: {{ .Values.streamParkPersistent.class }}