apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aidsp-prj-apps
spec:
  generators:
  - git:
      repoURL: https://gitlab.sdsp-stg.com/paas/argocd-mono/stg.git
      revision: HEAD
      directories:
        - path: "aidsp-prj-manifests/*"
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: aidsp
      source:
        repoURL: https://gitlab.sdsp-stg.com/paas/argocd-mono/stg.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true