apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helmchart-apps
spec:
  generators:
  - git:
      repoURL: https://gitlab.sdsp-stg.com/paas/argocd-mono/stg.git
      revision: HEAD
      directories:
        - path: helmcharts/*
  template:
    metadata:
      name: "{{path.basename}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
        argocd.argoproj.io/compare-options: ServerSideDiff=true
    spec:
      project: default
      source:
        repoURL: https://gitlab.sdsp-stg.com/paas/argocd-mono/stg.git
        targetRevision: HEAD
        path: "{{path}}"
        helm:
          releaseName: "{{path.basename}}"
          valueFiles:
          - "values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true