apiVersion: v1
appVersion: 2.0.1
description: VerneMQ is a high-performance, distributed MQTT message broker
name: vernemq
version: 2.0.1
icon: http://www.stickpng.com/assets/thumbs/58482b21cef1014c0b5e4a24.png
dependencies:
- name: vernemq
  version: "2.0.1"
  repository: "https://vernemq.github.io/docker-vernemq"