vernemq:
  replicaCount: 3

  image:
    repository: vernemq/vernemq
    tag: 2.0.1-alpine

    pullPolicy: IfNotPresent

  service:
    # Can be disabled if more advanced use cases require more complex setups, e.g., combining LoadBalancer and ClusterIP for internal and external access. See also issue #274.
    enabled: true
    # NodePort - Listen to a port on nodes and forward to the service.
    # ClusterIP - Listen on the service internal to the cluster only.
    # LoadBalancer - Create a LoadBalancer in the cloud provider and forward to the service.
    type: NodePort
    mqtt:
      enabled: true
      port: 1883
      # This is the port used by nodes to expose the service
      nodePort: 31279
    mqtts:
      enabled: false
      port: 8883
      # This is the port used by nodes to expose the service
      nodePort: 8883
    ws:
      enabled: false
      port: 8080
      # This is the port used by nodes to expose the service
      nodePort: 8080
    wss:
      enabled: false
      port: 8443
      # This is the port used by nodes to expose the service
      nodePort: 8443
    api:
      enabled: false
      type: ClusterIP
      port: 8888
      nodePort: 38888
      annotations: {}
    annotations: {}
    labels: {}


  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    storageClass: ceph-block

  additionalEnv:
    - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
      value: "on"
    - name: DOCKER_VERNEMQ_ACCEPT_EULA
      value: "yes"
    - name: DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS
      value: "3,4,5"