apiVersion: v2
name: cert-manager
description: A Helm chart for cert-manager
version: 1.15.3
appVersion: 1.15.3
home: https://cert-manager.io
icon: https://raw.githubusercontent.com/cert-manager/community/4d35a69437d21b76322157e6284be4cd64e6d2b7/logo/logo-small.png
dependencies:
- name: cert-manager
  version: 1.15.3
  repository: https://charts.jetstack.io