apiVersion: v2
appVersion: "4.0.1"
description: Apache Superset is a modern, enterprise-ready business intelligence web application
name: superset
icon: https://artifacthub.io/image/68c1d717-0e97-491f-b046-754e46f46922@2x
home: https://superset.apache.org/
maintainers:
  - name: craig-rueda
    email: craig@craigrueda.com
    url: https://github.com/craig-rueda
version: 0.12.11
dependencies:
  - name: superset
    version: 0.12.11
    repository: http://apache.github.io/superset/