apiVersion: v2
name: openmetadata
description: A Helm chart for OpenMetadata on Kubernetes
type: application
version: 1.5.8
appVersion: "1.5.8"
home: https://open-metadata.org/
sources:
  - https://github.com/open-metadata/OpenMetadata
  - https://github.com/open-metadata/openmetadata-helm-charts
keywords:
  - metadata
  - data-science
  - data
  - machine-learning
  - automation
  - big-data
  - bigdata
  - artificial-intelligence
  - datascience
  - data-engineering
  - data-catalog
  - metadata-api
  - governance
  - data-profiling
  - metadata-management
  - dataengineering
  - dataquality
  - bigdataanalytics
  - datadiscovery
maintainers:
  - name: OpenMetadata
    email: support@open-metadata.org
icon: https://open-metadata.org/assets/favicon.png

dependencies:
- name: mysql
  version: "9.7.2"
  repository: "https://charts.bitnami.com/bitnami"
  condition: mysql.enabled
- name: airflow
  version: "8.9.0"
  repository: "https://airflow-helm.github.io/charts"
  condition: airflow.enabled
- name: opensearch
  version: "2.12.2"
  repository: "https://opensearch-project.github.io/helm-charts/"
  condition: opensearch.enabled
- name: openmetadata
  version: "1.5.8"
  repository: "https://helm.open-metadata.org/"