apiVersion: v2
appVersion: "3.8"
description: "Strimzi: Apache Kafka running on Kubernetes"
name: strimzi-kafka-operator
version: 0.43.0
icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
keywords:
- kafka
- queue
- stream
- event
- messaging
- datastore
- topic
home: https://strimzi.io/
sources:
- https://github.com/strimzi/strimzi-kafka-operator
maintainers:
- name: Frawless
- name: ppatierno
- name: samuel-hawker
- name: scholzj
- name: tombentley
- name: sknot-rh
- name: PaulRMellor
- name: im-konge
- name: see-quick
dependencies:
- name: strimzi-kafka-operator
  version: 0.43.0
  repository: oci://quay.io/strimzi-helm
- name: kafka-ui
  version: 0.7.6
  repository: https://provectus.github.io/kafka-ui-charts